const article = 
`Since his literary debut in 1980, Jan Kjærstad has distinguished himself as one of Norway’s most popular, cosmopolitan, and innovative authors, but also as a respected literary theorist and active participant in cultural debates about what it means to be Norwegian. Having lived in Harare, Zimbabwe for two and a half years (1989–1991), traveled extensively, and devoted himself to keeping up with contemporary literature and critical theory from around the world, Kjærstad brings an unparalleled mix of international erudition and thoroughly grounded everyday Norwegianness to the Norwegian literary scene. As editor of the literary journal Vinduet in the late 1980s, Kjærstad was one of the first Norwegians to recognize the importance of discussions on literary postmodernism that were going on throughout the western world and introduced some of these ideas to a Norwegian audience for the first time.

Kjærstad employs a wide range of postmodern elements in his fiction, but also consistently blends multiple genres and styles so that his texts can never be classified simply as, for example, postmodernist, mystery, biography, or romance. Rather, they are always hybrids. In “En poetikk for 80-årene” (A Poetics for the 1980s), he advocates a new “kombinasjonspoetikk” (combinational poetics), emphasizing not only the place of content, form, and language in his literature, but also the importance of a metalevel, looking at larger patterns and permutations. Kjærstad practices this by fluidly blending metafiction and complicated, original narrative structures with a seamless blend of high and low cultural references and allusions from extremely diverse fields. His unique and popular combination of the cerebral and the mundane has earned him a reputation as an alluring storyteller, but also garnered him criticism from defenders of the traditional, old school literary canon, especially Norway’s social realists and their proponents.

With a cand. theol. (roughly equivalent to a master’s degree in theology) from the University of Oslo, Kjærstad has been aptly dubbed a literary ecumenicist for his predilection for juxtaposing multiple points of view and ultimately challenging the reader to make the final decisions. One unifying theme throughout his authorship is the question, “What is a human being?” He is one of few Norwegian writers to have garnered international recognition with literary awards such as the German Henrik Steffens Prize in 1998, the Swedish Academy of Literature’s Dobloug Prize in 2000, and the Nordic Council’s Literary Prize for the year’s best work of fiction from the Nordic region in 2001.

Jan Kjærstad was born on March 6, 1953 in the Oslo suburb of Grorud. His maternal grandfather was a sailor and fisherman. His paternal grandfather was a farmer and industrial worker. His mother, Ragnhild Jensen, worked for a telecommunications and cable systems company, Standard Telefon og Kabelfabrikk (now Alcatel). His father, Leif Asbjørn Kjærstad, was a furniture agent. Kjærstad’s younger brother Tor was born in 1955. Kjærstad describes his childhood in 1950s Grorud as practically ideal. Well before expansion from Oslo really took hold, he spent his free time with other local children playing on local farms and fishing in the creek. As he grew up, construction sites popped up around Grorud, rapidly building large apartment complexes to resolve the postwar housing crunch. From a schoolchild’s perspective, the construction sites provided exciting places to play and climb on the scaffolding. Kjærstad was an exceptionally shy child who disliked being in the spotlight. He dreaded school pageants, being asked to read aloud in English class, selling tickets at the door, and saying hello to strangers. He played the piano for ten years, between the ages of eight and eighteen, and played in several bands, both electric guitar and keyboards. During his school years, Kjærstad enjoyed sports and was active in track and field, soccer, and orienteering. He also won awards in skiing and ice-skating.

He went on to study theology at the University of Oslo for six years. There, his theses on “The Synoptic Tradition and the Historical Jesus. Bultmann’s Form Critical Method and His Authenticity Criteria. A Study of Bultmann’s Authenticity Criteria in the ‘Prophetische und Apokalyptische Worte’ section of his Die Geschichte der synoptische Tradition“ (1978) and “Freedom and Necessity as Social Ethical Problems: A Comparison of Reinhold Niebuhr’s and Leszek Kolakowski’s Social Ethics with a Special Emphasis on So-Called ‘Laws of Necessity’ in Social Life” (1979) earned him the theology department’s highest grade, a laudabilis prae ceteris. Even in his early academic work as a theology student, it is clear that Kjærstad did not shy away from theory and was particularly drawn to questions of form, authenticity, and what it means to be an individual. He was well on his way towards an academic future, envisioning himself first as a scholarly assistant, then earning his doctorate, and then hopefully an academic position. But then, in the spring of 1978, at the age of twenty-five, Kjærstad suddenly felt the urge to write fiction. He likens the change to a quantum leap, from academic theology’s world of existential choices, facts, truth, and scholarship to popular fiction’s world of imagination, creativity, lying, and fumbling.

In the essay “Kvanteloven” (The Quantum Law) in Veien langs linjene, eller hvordan vi ble forfattere (The Path Along the Lines, or How We Became Authors, 1993), Kjærstad describes how he became an author. One year before he completed his university degree, he suddenly felt an uncontrollable need to write. He had been reading books like Villy Sørensen’s Sære historier (Strange Stories, 1953), Hermann Hesse’s Narziß und Goldmund (Narcissus and Goldmund, 1930), and particularly Pär Lagerkvist’s Det eviga leendet (The Eternal Smile, 1920), where in the end the reader meets God as a diminutive old man sawing wood. Sitting on the subway after reading Lagerkvist’s story, Kjærstad had an epiphany that that one story said more than all the theology in the world. He sold his musical equipment and decided to take up writing. He felt that his transition to writing should be marked by leaving Norway and decided to set out on his first truly independent trip, not as a conventional, herd-mentality tourist as he felt he had been on his earlier Inter-Rail trips, but as an explorer, straying off the beaten path.

He spent the summer in Corsica where he wrote two hundred pages in six weeks. Joking that he has not been able to match that speed of production later in his career, he also confesses that four large publishers emphatically rejected that first work, Fjelldalen (Mountain Valley). Looking back at his rejected manuscript in 1993, Kjærstad saw that despite its formal weaknesses, it was nonetheless a collection of tales that crystallized his principal beliefs at that time, his basic view of the human condition. By writing, he felt he had given his own unfairly treated imagination a chance. In that first manuscript, he recognized his rejection of dogmatics and his escape from theology’s pursuit of the Truth and unambiguous answers. Instead, he opted for the narrative arts because they permit an alternative form of understanding, leave room for intuition, open up complementary points of view, and are inclusive. They are not “either/or” but “both and.”

Kjærstad never returned to traditional academia, going on instead to become one of Norway’s most widely read and popular writers. In 1980, Aschehoug published his first work, a collection of fourteen short stories entitled Kloden dreier stille rundt (The Planet Quietly Revolves). The stories deal with widely varying topics including pollution, drug addiction, the suggestive power of mass media, racism, and the arms race. Kjærstad’s propensity to experiment with form and perspective is clear; many of the stories focus on communication problems, misinterpretations, and wasted opportunities for understanding. Norwegian critics, perhaps affected by their awareness of his background in theology, heralded him as an exciting and “spiritual” first-time author with a delicate contemporary awareness. That same year, Kjærstad began living with his future wife, Astrid Nøstvik, who works for the Norwegian Ministry of Foreign Affairs.

Kjærstad’s true literary breakthrough came in 1982 with the release of his first novel, Speil: leseserie fra det 20. århundre (Mirrors: A Series of Readings from the Twentieth Century), which traces protagonist David Dal’s odyssey through the twentieth century. He grows up in Trondheim, studies in Paris, and becomes an engineer. However, Dal comes to see that technology can be used to destructive ends, specifically in terms of the arms race and war, and eventually changes careers, becoming not just a painter, but a world-renowned artist. The Faust motif pervades Speil and Kjærstad admits that even as a child he was fascinated with the Mickey Mouse version of Goethe’s “Der Zauberlehrling” (The Sorcerer’s Apprentice, 1797) (van der Hagen, 160). Tracing decisive episodes in protagonist David Dal’s life and key events in Western history, the voluminous text’s details finally become pieces in a three-dimensional puzzle, which, as always with Kjærstad, readers are left to assemble the puzzle on their own.

Kjærstad has described these first two books as part of a dialog with modernism, motivated in part by Ezra Pound’s modernist demand to “make it new.” By placing conflicting elements and perspectives side by side, Kjærstad believes authors have the opportunity to reveal secret connections and surprising similarities. In part, this is what led Geir Mork to characterize Kjærstad as “ein litterær økumenikar” (a literary ecumenist) (van der Hagen, 152).

Just as his first two books comprise Kjærstad’s dialog with modernism, he calls his next two a contextual dialog with postmodernism. Kjærstad was part of a generation that broke with the social realist trends that had been prevalent in Norwegian literature in the 1970s. Kjærstad believes that literature does not reflect reality – it is reality; writing brings something new into existence. By the mid 1980s, as Kjærstad entered his thirties, he had found his calling. Writing as a profession gave the formerly shy child a chance to express himself, a way to remain somewhat of an outsider, but still participate. Plus, Kjærstad jokes in “Kvanteloven,” writing is a great lifestyle. An author gets to read, travel, narrate, interview, research, meet new people … a perfect mix of the abstract and the concrete, practice and theory, idea and perception, the cloister and the pulsing world at large. By writing, narrating, one can be both Narcissus and Goldmund at the same time.

With the 1984 release of his metafictive detective novel, Homo falsus eller det perfekte mord (Homo Falsus or The Perfect Murder), Kjærstad’s acclaim was sealed, both in terms of popular sales and critical acclaim. Critics agreed that Kjærstad had created a truly original work, both in its form and its content, and he was awarded the Norsk Kritikerlags (Norwegian Critics’ Association) prize for adult fiction. Critics, particularly in Denmark and Sweden but also in Norway, also heralded this as Norway’s first postmodern novel. In many ways, Kjærstad captured the pulse of the 1980s in this highly innovative, metafictive discussion of the individual’s place in the new information society. In Homo falsus, as Kjærstad told the newspaper Dagbladet, the web, not the spider, is of the utmost importance. The novel is composed of repeated variables, factual building blocks that form four major sections. Kjærstad suggests that this is in part the result of the university course, “EDB for humanister” (Computers for Humanists), he was taking at the time where he encountered Pascal and programming loops. In each of the novel’s four sections, a woman who calls herself Greta after film icon Greta Garbo sends a married man flattering letters, meets him in a nightclub, and then takes him to a borrowed apartment. There, using both her body and her intellect, she ritually seduces the man and, through a tantric sexual act, causes him to vanish just as he reaches the point of orgasm. She then sends his clothing home to his family. In the first three sections of the book, Greta consecutively does away with Paul, Alf, and Jacob; in the final section, the book’s narrator becomes her fourth victim.

Kjærstad’s text is distinctive in the extent to which he carries metafiction. The text’s third person narration is frequently interrupted by chapters written in the first person by the text’s male narrator, describing everything from what he had for lunch to how he created the character of Greta and wrote his book, presumably Homo falsus. By the end of the book, Greta has become her own narrator, a subject in her own right rather than the object of someone else’s story, and the male narrator is locked up in a psychiatric institution, the scandal of which ironically improves sales of his book, presumably Homo falsus. Kjærstad never resolves which of the two really narrates the book. Rather, the narrative situation resembles M.C. Escher’s “Drawing Hands” (1948) where two hands are simultaneously drawing each other, forming a circular, self-creating system. This reflects one of the causes Kjærstad advocates in his theoretical writings as well, that of moving beyond Bakhtin’s polyphonic novel, juxtaposing multiple voices, to what he dubs a polytheistic novel, juxtaposing multiple life philosophies and world views.

The book was heralded as a postmodern thriller by reviewers outside of Norway, but met mixed reviews in Norway. The majority of critics responded quite favorably, applauding Kjærstad’s intelligence, innovation, and inclusion of societal references from both high and low cultural sources, everything from Ibsen and Adorno to Elvis and Playboy magazine. Ironically his detractors focused on the same things, criticizing Kjærstad for providing too much of a good thing – he has been called too erudite, too familiar with literature and literary theory from outside of Norway, too up to date in terms of electronic media and computers, and too popular with readers. He has been particularly criticized for the “encyklopedisk vald” (encyclopedic violence) (Kongslien, 105) he perpetrates on his readers by sprinkling his texts with overwhelming numbers of factual references, some authentic and some purely lies. An example of this is Alf’s death scene in Homo falsus, as Greta eliminates him by bringing him to orgasm:

Venner, applauder, komedien er over, skulle Beethoven ha sagt idet han døde.
Et tu Brute, sa Cæsar.
Mer lys! Mer lys! sa Goethe.
Det var et flott slag golf, gutter, sa Bing Crosby.
Jeg gjør det igjen, sa Hernán Cortés.
Alf Skjønfeldt sa ingenting.

(“Applause, friends, the comedy is over,” Beethoven is to have said as he died.
“Et tu, Brute,” said Ceaser.
“More light! More light!” said Goethe.
“That was a great game of golf, fellas,” said Bing Crosby.
“I’ll do it again,” said Hernán Cortés.
Alf Skjønfeldt said nothing). (173)

Note that Kjærstad both elevates Alf by comparing him with such famous company, and denigrates him by leaving him speechless while the others all uttered final phrases that went down in history. On another level, the citations communicate to the reader that Alf is about to die without actually saying so. While some critics liken Kjærstad’s work to a “faktahelvete” (hell of facts), Kjærstad himself prefers to call it a paradise of language, something appropriate to a contemporary multimedia, TV-driven society with its sound bites, film clips, and hypertext. Looking back, Kjærstad has called Homo falsus his most personal book, a camouflaged self-portrait. Of all the characters he has created, he says he most resembles Greta.

From 1985–1989 Kjærstad took on a new role as the editor of the Norwegian literary journal, Vinduet (“The Window”). While there, he played an active part in introducing postmodern ideas to Norway. He encountered opposition from the Norwegian press and old school academics for this. As scholar and critic Eivind Røssaak discusses in Det postmoderne og de intellektuelle (The Postmodern and the Intellectual; 1998), Norwegian academics were remarkably late in contemplating postmodernism, partly because of a widespread misunderstanding that it was equivalent to nihilism, and partly because of a reactionary fear of leveling the playing field between high and low culture. In his editorial work, his theoretical writings, and his fictional writings Kjærstad’s open minded, insightful consideration of postmodern theory has set him apart from the majority of Norwegian authors and literary theorists.

As editor of Vinduet, Kjærstad selected texts and interviewed many of the world’s leading literary theorists and authors, making their ideas available in Norwegian translation and to a specifically Norwegian audience for the first time – including postmodern thinkers such as Baudrillard, Lyotard, Perniola, Serres, and Deleuze. While few Norwegian journalists had mentioned postmodern authors such as Italo Calvino or Thomas Pynchon, Vinduet did not hesitate in doing so under Kjærstad’s editorship. Vinduet also profiled many non-canonical Norwegian authors including Steinar Løding, Lars Amund Vaage, Torgeir Schjerven, Karin Moe, Ole Robert Sunde, Hanne Bramness, and Hans Herbjørnsrud. Kjærstad’s experiences at Vinduet opened him up to thinking about literary theory and literature from a global perspective, not merely a Norwegian one. He took his contribution to the Norwegian literary milieu seriously, relishing his opportunity to open people’s eyes to new ways of thinking.

While acknowledging postmodern influences in his own writing, Kjærstad has consistently held that he does not consider himself a postmodernist. In fact, in an online meeting with Dagbladet readers (February 23, 2000) he goes so far as to say, “Jeg tror ikke det er nasjonalgenetisk mulig for en nordmann å bli postmodernist” (I don’t believe it is nationally genetically possible for a Norwegian to be a postmodernist). This is hardly surprising in light of his earlier assertion that “Norge er en provins. Derfor kom modernismen aldri til Norge” (Norway is a province. Hence, modernism never came to Norway) (Menneskets Matrise, 87). Despite Kjærstad’s repeated claims that modernism and postmodernism never reached Norwegian literature, many academics and literary critics, both those who extol and those who denigrate Kjærstad’s literary production, disagree with Kjærstad. Particularly among scholars working outside of Norway, Kjærstad is widely recognized as one of Norway’s leading postmodernists.

What is uncontested is that, both as an author and as an editor, Kjærstad was part of a new generation in Norway that wished to break the monopoly an older generation, typified by their association with the journal Profil, had on defining politically radical literature. Kjærstad’s generation broke away from the social realism that had been so prevalent in Norwegian literature in the 1970s. In fact, in 1986, Kjærstad challenged the then fervently Maoist author Edvard Hoem to a literary duel: “Her, en hanske smekket i fjeset, Hoem! Både Hoem og jeg kommer med nye romaner til neste år. Jeg ser på meg selv som en eksponent for den brokete 80-tallslitteraturen Hoem så sterkt misliker … Jeg utfordrer deg, Hoem: hvem av oss skriver den beste boka?” (Here, a glove smack to the face, Hoem! Both Hoem and I have new novels coming out next year. I consider myself an exponent of the varied literature of the 80s that Hoem so dislikes … I challenge you, Hoem: which of us will write the best book?) (Menneskets Matrise, 178).

An active participant in cultural debates, many of the essays Kjærstad wrote during the 1980s were collected and published as Menneskets matrise, litteratur i 80-årene (The Matrix of Man: Literature in the 1980s), which was released in 1989. Here, Kjærstad presents his take on major trends in 1980s Norwegian fiction, particularly a new generation of authors making concerted efforts to break with past trends. Some critics, mostly those who did not care for newer literary trends, felt that Kjærstad’s essays were too polemical.

In 1987, Kjærstad released what was dubbed his most difficult, ambitious novel to date, Det store eventyret (The Great Fairy Tale). Part adventure story and part fairy tale, borrowing from science fiction and postmodernism, Kjærstad’s satirical, fantastic novel features Oslo as the capital of a tropical country including volcanic mountains, palm-strewn beaches, and minarets along the central Karl Johan’s street. Kjærstad traveled to Mauritius to write part of Det store eventyret, feeling he needed that type of setting for the novel he was envisioning. In this allegorical tale, most Norwegians are black and Norway is part of the third world. The book’s protagonist, Peter Beauvoir, is the photo editor for a fictional, world-renowned encyclopedia. Beauvoir’s quest to solve the riddle of an old fairy tale, find, and win the mysterious Shoshana Moira drives the story around the world. He constantly faces unfamiliar situations and everyone he asks about Shoshana tells him conflicting stories about who she is. During his search, he encounters text fragments from a collection of fairy tales called Hazar that may just be the key to winning her, but in order to do so he must first solve their riddle. Peter must figure out the concealed identities of Hazar’s main characters, Ado (Adolf Hitler) and Urchi (Winston Churchill).

Det store eventyret is also part bildungsroman; although Peter starts out as one-dimensional as the photographs he takes, through his readings and studies he becomes an educated man. In some ways the text is a classic love story, in other ways it is also remarkably different. Kjærstad takes the idea of a straightforward love story to a new level, infusing it with postmodern elements, including an extreme degree of intertextual referentiality, keeping the narrator’s identity secret, and elevating the quest for the loved one above the loved one herself. In “Is Nothing Sacred?” in Imaginary Homelands: Essays & Criticism, Salman Rushdie describes this latter technique, “the elevation of the quest for the Grail over the Grail itself” (422), as a central aspect of the postmodern condition. This is precisely what Kjærstad does in Det store eventyret.

In an elaborate display of intertextuality Kjærstad weaves a tapestry of allusions to some of the pillars of world literature into the text, including a pastiche of references to the Old Testament, the Arabian Nights, and the Odyssey as well as books by Flaubert, Grass, Céline, and Faulkner. He also plays with different types of typography, occasionally placing parallel columns side by side on the same page, allowing the reader to choose how to read the text. In Det store eventyret, writing becomes love’s most important tool – the quest for knowledge and the quest for love fuse into a dual search to decipher the riddle of a fairy tale and a woman.

The book received mixed reviews, often from the very same critics. Øystein Rottem, for example, described it in a review in Arbeiderbladet as a book that “imponerer og irriterer på samme tid” (is impressive and irritating at the same time) (July 25, 1987). Rottem was impressed by Kjærstad’s virtuoso aesthetic construction, the rich allure of the mystery he created, and the link between erotic desire and textual interpretation. However, like many critics, Rottem found the idea of Norway as a tropical island and the text’s typographical nonconformity to be artificial and unsuccessful.

Kjærstad married Astrid Nøstvik in 1988. The couple had two daughters, Marit (born in 1985) and Elisabeth (born in 1988). In 1989, Kjærstad wrote his first children’s book, Jakten på de skjulte vaffelhjertene (The Hunt for the Hidden Waffle Hearts) and selected and adapted tales for the two-volume Tusen og én natt (The Arabian Nights). He later wrote a children’s book, Hos Sheherasad, fantasiens dronning (With Scheherazade, Imagination’s Queen) (1995) inspired by the character from the Arabian Nights. After he left Vinduet, Kjærstad and his family lived in Harare, Zimbabwe, for two and a half years, between 1989 and 1991.

His next novel, Rand (Brink; 1990), has been compared to Hamsun’s Sult (Hunger; 1890), as both texts contain first person narrators who wander Oslo’s streets in a world that seems devoid of meaning. Unlike Hamsun’s book, a keystone of Norwegian modernism, Rand is a contemporary crime novel with an intellectual twist. In the text, a newspaper article reports that a man was found dead in the middle of the street behind the Deichmanske Library in Oslo, the first in a series of unexplained deaths in the city. There is evidence that a serial killer has murdered the victims, each with a surprising set of qualities and interests. Who is this unscrupulous and impulsive killer on the loose in postmodern Oslo? Things become even more complicated when the murderer, a leading computer expert, is put in charge of coordinating the police’s computer files on the case. Gradually, as he learns more and more facts about his victims, he begins to realize that they hold the key to the riddle of contemporary civilization. Rand takes readers on a sobering, urgent journey into Western culture, hinting that something incomprehensible and perhaps monstrous lurks behind visible reality. In discussing Rand, Kjærstad points out that good stories are sometimes repulsive, citing Hamsun’s Mysterier (Mysteries, 1892), Camus’s L’Étranger (The Stranger, 1942), and Conrad’s Heart of Darkness (1899) as examples (van der Hagen, 156). He also names the assassination of Swedish president Olof Palme and Rudolf Otto’s Das Heilige (Idea of the Holy, 1917) as influences in writing this book (Menneskets Felt, 68 and Dagbladet, 10 May 1999).

Rand is an ode to Kjærstad’s hometown, Oslo, and a commentary on the cosmopolitanization it was experiencing at the time. Ironically, it also clearly delineates a trend in the way Kjærstad’s books have been received by his hometown media. Although Rand received glowing reviews outside of Norway, Aftenposten’s reviewer Håvard Rem panned the novel (10 August 1990). Indeed, Rand’s reception is representative of an overall trend in the way Kjærstad’s work has been received, generally far more positively in the foreign press than at home. In his critique of Linn Ullmann’s review of Peter Høeg’s Kvinden og aben (The Woman and the Ape, 1996), Kjærstad explains why this dichotomy might exist. He describes both the problem, that so many Norwegian reviewers are only good at judging traditional novels, and the solution: critics who can write seriously and informatively about “de nye ‘urene’ bøkene som smelter litterære sjangrer og tradisjoner sammen” (the new ‘impure’ books that blend literary genres and traditions together) (Menneskets Felt, 208). Kjærstad argues that foreign reviewers, as well as Norwegian authors and the Norwegian reading public, have already made this leap.

While Kjærstad has continued to reside in Oslo, he has also traveled extensively abroad. He challenges himself as an author to meet the demanding standards set on the world stage by authors he identifies with, authors which include Saul Bellow, Inger Christensen, Don DeLillo, Marguerite Duras, Haruki Murakami, Iris Murdoch, Kenzaburo Oe, Michael Ondaatje, Amos Oz, Orhan Pamuk, Richard Powers, Salman Rushdie, and Graham Swift. Rand, Kjærstad explains, has far more in common with Orhan Pamuk’s Kara Kitap (The Black Book, 1990), which features Istanbul much as Rand features Oslo, than with other contemporary Norwegian novels. Indeed, Kjærstad is renowned as one of Norway’s most captivating storytellers, and at the same time many Norwegians feel that he has an un-Norwegian sense for humanity’s arsenal of possibilities. He is very much an author with one foot in Norway and the other in the rest of the world.

In the early 1990s, Kjærstad spent a week in Copenhagen with playwright and author Jon Fosse teaching at Poul Borum’s writing school. The two authors spent their evenings arguing about literature, until they ultimately discovered how much they had in common. Together they created the journal Bøk (Beech) and since 1993 it has contributed to discussions of Norwegian and international literature and literary theory. Fosse and Kjærstad also choose the title as it is a play on the Norwegian word for “book(s),” a form somewhere between the singular (“bok”) and plural (“bøker”) forms, which they chose to highlight the space between the individual (psychological literature) and the collective (social realist literature). As remarkably different authors, Kjærstad and Fosse have had some lively debates on literature and theory. In one, they outline two schools of fiction, one that emphasizes the fabulous epic inventiveness (Joyce, Grass, Rushdie) and one that emphasizes the distinctive poetic voice (Beckett, Handke, Bernhard). Kjærstad favors the former and Fosse the latter. Similarly, they disagree over the preeminence of metaphor or metonymy in literature, with Kjærstad favoring the former and Fosse the latter.

In 1997, Kjærstad and Astrid Nøstvik divorced. That same year he published a collection of his essays, readings, and reflections from the 1990s, in Menneskets felt (The Human Sphere). Here he discusses a wide variety of theoretical topics, demonstrating a level of skill, intellectual breadth, and global erudition that is practically unparalleled among contemporary Norwegian authors. His comments on the relationship between modernism and postmodernism are some of the most accessible of any European writer to date. Kjærstad likens the modernist approach to identity to a magnifying glass, focusing on plumbing the depths of an individual’s mind, whereas the postmodernist approach is more like a prism used to spread open and look at the many facets of an individual (Menneskets felt, 268). Instead of searching for a center, he says, a postmodern author looks at the broad web of interconnected positions that define an individual’s perimeters. In “Fra ubevisste sjeleliv til ekspanderende univers: et bud på romanens videre utvikling” (From the psychology of the unconscious to an expanding universe: a bid for the novel’s further development), he writes,

Om vi tyr til Ibsen og Peer Gynts selvrefleksjoner mens han plukker fra hverandre en løk, er problemet i dag ikke så mye det vertikale, at mennesket har en kjerne, men det horisontale, at mennesket består av flere løker. Menneskets identitet er større enn vi tror. Det holder ikke å sammenligne et individ med én løk, individet er et nett med løk.

(If we refer to Ibsen and Peer Gynt’s self reflections while pulling apart an onion, the problem today is not so much the vertical, that the individual has a core, but the horizontal, that the individual consists of many onions. The individual’s identity is larger than we think. It no longer holds to compare an individual with one onion; the individual is a network of onions.) (Menneskets felt, 268)

One unifying trait of Kjærstad’s literary production is a desire to answer the question of what it means to be a human being. He feels that very little has been done with this question since Virginia Woolf’s Orlando (1928), the biography of one individual whose life encompasses not only several centuries but also both genders. Throughout his career, Kjærstad has striven to continue from where Woolf left off, to write about human identity in a different way. In doing so he has consistently and metafictively transgressed genre delineations and created a number of memorable postmodern subjects. Similarly, where radical attempts to expand the nature of the novel are concerned, he argues that experimentations with narrative frame have not progressed much since Conrad’s Lord Jim (1900) and Faulkner’s Absolom, Absolom! (1936). Kjærstad believes authors can use narrative frames and levels to revitalize otherwise stagnant narrative arts. He associates this with a trend from modernism to postmodernism, or as he puts it, from the stethoscope to the telescope. While many modernist texts sought to enter further and further into a given narrative frame, frequently delving well into the mind of one individual, many postmodernist texts step further and further back, looking at the progressively widening frameworks in which each individual exists.

When he released his epic trilogy about fictional Norwegian TV personality Jonas Wergeland – Forføreren (The Seducer; 1993), Erobreren (The Conqueror; 1996), and Oppdageren (The Discoverer; 1999) – Kjærstad did just what he had described in Menneskets felt: he took the biography of an individual one step beyond Virginia Woolf’s Orlando and moved the art of experimenting with narrative frame a step beyond Conrad. Internationally, Kjærstad received rave reviews and enormous popular success for the trilogy as well as prestigious literary awards including the Aschehoug prize in 1993, the German Henrik Steffens prize in 1998, the Dobloug prize in 2000, and the Nordic Council’s literature prize in 2001. In Norway, however, many reviewers criticized Kjærstad for not writing a chronological, traditional story, while ironically also commenting that his texts were not especially original. They disparaged him for “eksotisme og name dropping” (exoticism and name-dropping). Norwegian critics characterized Jonas Wergeland, Kjærstad’s post-Woolfian individual, as a “datahjerne uten av-knapp” (computer brain without an off-button) and his experimentations with narrative frame as a clichéd and ridiculous need to foreground the text’s skeleton and construction (Dagbladet, 3 August 1993).

In part, Kjærstad’s novels garnered negative attention from Norwegian reviewers because they were so different, in part because they touched a nerve with their somewhat too astute criticisms of Norwegian society and national self-righteousness, and in part because Jonas Wergeland broke with the strongly held Janteloven principles of modesty, enforced mediocrity, and not drawing attention to oneself that were outlined by Aksel Sandemose in En flyktning krysser sit spor (A Fugitive Crosses His Tracks; 1933). Although Oppdageren received a much more positive reception in Norway than the previous two books, Norwegian reviews came nowhere close to the glowing praise of Danish reviewers. When the Norwegian committee, consisting of Linn Ullmann and Einar Økland, did not nominate Oppdageren for the Nordic Council’s literature prize in 1999, some Danish critics protested, threatening to nominate Kjærstad themselves. The following year, the Norwegian committee, then consisting of Hans H. Skei and Oskar Stein Bjørlykke, nominated Oppdageren, and in 2001 Kjærstad won the distinguished prize.

In his Wergeland books, Kjærstad continues to be a master of narrative innovation, capturing instants from Jonas’s life in about two hundred short narratives throughout the three books, painting the life of a human being as a tapestry of innumerable stories, in complementary and often conflicting versions, ignoring any strict chronology, continuity, or causality. Kjærstad leaves the reader to ponder the true story of Jonas’s life. Inspired by works including the Argonautica, Faust (1808), Peer Gynt (1875), the Mahabharata, and The Satanic Verses (1988), Kjærstad’s narrative is deliberately playful and experimental, using the entire palette of techniques contemporary fiction has to offer. Metafiction serves to foreground the pervasive questions of what shapes a life, what moments in a person’s life are decisive, and whether there is such a thing as objective truth. All three books deal with questions of identity and how a person’s life is constructed. They are also about sexuality and relationships between men and women, and not least of all about Norwegian society in the latter half of the twentieth century. Kjærstad has a penchant for biting satire, but also spins an impressive song of praise to the imagination and to people’s ability to change perspectives. He has been credited with reinventing the biography and writing one of the best examples of a postmodern bildungsroman.

The three books each present different versions of Jonas Wergeland. Forføreren presents a youthful, open, inquisitive Jonas born for success, a gifted, charismatic hero whom talented women throw themselves at. Indeed, there are numerous similarities between Kjærstad’s Jonas and Kierkegaard’s Johannes, the protagonist of “Forførerens Dagbok” (The Seducer’s Diary) from Enten–Eller (Either–Or, 1843). In Erobreren, Kjærstad presents Jonas in a more negative light, covering his professional adult life as a television personality and his rootless travels. He is both egocentric and ethnocentric, a weak man struggling to overcome his own mediocrity and destiny, a man with an enormous need for security and control. Here it is his very mediocrity that attracts women. He beats his wife and is convicted of her murder. The two books present complementary portraits of Jonas Wergeland. The third book, Oppdageren, resolves some of the unanswered questions from the first two and presents a whole new take on Jonas, particularly his experiences in prison and afterwards. Readers see Jonas from the inside, a person who seeks and achieves external success, but is emptied in the process, becoming an internal fiasco. He recognizes his own inconsequence, takes the blame for his wife’s suicide, and by atoning becomes a wiser, richer man, thankful for the opportunity to begin anew and able to see the decisive importance in his life of someone outside himself. Where before Jonas experienced confrontations and challenges, he is now able to develop truly meaningful interpersonal relationships. Ultimately, one of the books’ messages is that only love can make him whole, that a love that is patient and enduring can change everything.

In the trilogy, Kjærstad adroitly deconstructs the idea of a single objective truth, what postmodern theorists would call a grand récit. The apparently all-knowing, God-like narrator of Forføreren is revealed in Erobreren to have been the biased Indian-born ethnographer, Kamala Varma. She evokes a contemporary media narrator. Kjærstad remarks that viewers often accept television news as pure truth although they know that it has been scripted and edited, that it is only an excerpt of everything that happened in the world in the last twenty-four hours, that there are many stories not being told. Similarly, the authority of Erobreren’s narrator is downgraded in Oppdageren when it is revealed that Jonas’s sister Rakel narrated Erobreren. In Oppdageren, Jonas’s daughter Kristin’s narration is intermixed with sections narrated by Jonas himself. Kjærstad aggressively uses the mixed narrative throughout the trilogy to force readers to question objective truths. Reading Erobreren will change the reader’s understanding of Forføreren, and similarly reading Oppdageren will again force the reader to reevaluate the first two books. And although Jonas Wergeland is far from an average person, Kjærstad suggests that you can cast a light on the ordinary by writing about extreme situations and exceptional people.

During the 1990s, Kjærstad was also an active participant in a number of cultural debates that took place in Norwegian newspapers. In 1997, Dag Solstad published an essay in Aftenposten (27 June 1997) entitled “Om meddelelsens problem” (About Problems with the Message) that set off a firestorm of responses, Kjærstad’s among them. Solstad bemoans the passing of the way people thought about literature in the 1960s, asserting that the intellectual elite in 1990s Norway has abdicated its responsibility to look after the country’s cultural heritage. “Opplysningens lys må spres oven ifra og ned…” (The light of enlightenment must be spread downwards from above…), Solstad sermonizes before lamenting that the dependable, hierarchical literary canon of yore has been replaced with books that consumers like to read. Solstad summarizes, “…jeg forsto at en epoke var over, og at jeg selv befant meg i stor fare, som intellektuell” (…I understood that an era was over, and that I found myself in great danger, as an intellectual).

Kjærstad does not mince words in his response, “Klagesang fra vernet mann” (Lament from a Protected Man), criticizing Dag Solstad for his deeply conservative stance and for being an elitist who is out of touch with the role of literature in contemporary society. He accuses Solstad of belittling his own admirers, who are, after all, eager consumers of Solstad’s books, and of erroneously selling out the state of cultural life and intellectual pursuits in Norway. Solstad is so privileged and protected, so far removed from the fray, Kjærstad claims, “Det er ikke sant at den største nasjonalparken på Norges fastland heter Hardangervidda. Den heter Dag Solstad.” (It isn’t true that the largest national park in mainland Norway is the Hardanger Plateau. It’s Dag Solstad.) In his response, Kjærstad once again clearly marks himself as part of a newer generation of author than Solstad, one that is somewhat more in touch with the average Norwegian reader and not merely the country’’s intellectual elite.

Kjærstad also spoke out in Aftenposten in 1999, in connection with the Kosovo conflict, about the role of authors in political discourse. In much of Europe, unlike North America, there is a societal expectation that authors, as representatives of the intelligentsia, take a prominent, public role in debating political and social issues. Kjærstad elicited a wave of outraged responses when he suggested, among other things, that an author’s fiction is his or her most appropriate medium for influencing public thought. Kjærstad’s participation in this exchange demonstrates his unique position as both a Norwegian author and an author who considers his peer group to extend well beyond Norway’s borders.

Kjærstad showed this once again in January of 2000 when Anders Heger’s biography of Agnar Mykle triggered a debate on biography in Aftenposten. Kjærstad, fresh from his three-volume fictional biography of Jonas Wergeland, was an active participant, arguing that no biography provides the truth and that Norwegian biographies have been remarkably slow to break traditional molds when compared with those in other countries. A good biographer’s role, he argues, is to raise questions, not provide definitive answers. In what has become a pattern for Kjærstad, he bases his views on solid understandings of well-respected, international sources: in this case, Virginia Woolf, Roland Barthes, Hayden White, and Paul Ricoeur. His fellow debaters, often not as well read or as familiar with non-Norwegian discussions, find themselves outclassed and in some cases bordering on hysteria, accusing Kjærstad of “flinging around French and English names.”

In 2002, Kjærstad released his highly allegorical and semiotic Tegn til kjærlighet (Signs of Love), the story of a young woman’s love of writing and the often-intersecting forces of written text and oral narration. The reader follows the course of Cecilia’s life from her childhood at the side of her stonemason grandfather as he carved letters into headstones, to her early relationships with her friend Helene and a series of men including a typesetter and a font design instructor. She becomes a graphic designer working in advertising, but gives that up to follow her grandfather’s advice to “gjøre det umulige” (do the impossible). For Cecilia, this means crafting the perfect font, one that can actually create life, can open words up to a new meaning. She catches a glimpse of her ambition in the following excerpt:

Da jeg kom inn i stuen var vinduet dekket av dogg. Jeg kunne ikke se ut. Spontant skrev jeg navnet mitt, Cecilia, og øynet omgivelsene med en spesiell klarhet, gjennom bokstavene. Det var akkurat dette jeg ønsket meg av mine typer. At de skulle åpne. Gjøre meg seende. Vise en verden bak. (172)

(When I came into the room, the window was covered with condensation. I couldn’t see out. Spontaneously, I wrote my name, Cecilia, and saw my surroundings with a special clarity, through the letters. That was exactly what I wanted from my fonts. That they would create an opening. Allow me to see. Show a world behind.)

In the course of her quest, Cecilia encounters the epic oral storyteller and professional bread baker, Arthur, and the two fall in love. Arthur tells Cecilia his most intimate story, which she secretly writes down and publishes in English in her specially designed font as The Lost Story. This transformation of his oral tale into a written text ends up taking his life, although Cecilia manages to resurrect Arthur by wrapping him in text. Although this succeeds, he is nonetheless lost to her. Arthur and Cecilia’s romance is both a love story and, on another level, a symbolic treatise on the power of narration. In addition, the story is an allegorical consideration, not least of all, of genetic technology, where small manipulations to an alphabet of nucleotide bases often have profound effects on human life.

Kjærstad explained to Dagsavisen’s Turid Larsen that he drew on both the biblical story of Lazarus and tales from Indian mythology (26 September 2002). He emphasizes that his desire was to tell a story that combines clarity and simplicity with depth and a diffuse complexity, a rare combination that he observes, for example, in Joseph Conrad’s Heart of Darkness (1899) and some of Pär Lagerkvist’s novels. The book also has clear links to Don DeLillo’s The Names (1982), Peter Greenaway’s “The Pillow Book” (1996), and Karen Blixen’s “The Roads of Life” in Out of Africa (1938). True to Kjærstad’s carefully developed narrative style, he does not tell the story in plain chronological order. Rather, it is woven together in countless fragments and narrative morsels, which the reader must assemble to form an overall tapestry of the tale. Even his severest critics in Norway recognize the novel as storytelling composed of carefully crafted, technically masterful components.

In what has become a typical pattern in Kjærstad’s reception, Tegn til kjærlighet received overwhelmingly positive reviews in Denmark and split reviews in Norway. Those who disliked the novel criticized it for being overly symbolic, too clichéd, too international, and not traditional enough. Those who liked the novel praised it as a thought-provoking, richly narrated tale that achieved Kjærstad’s goal of balancing simplicity with depth. In addition to Denmark, rights to the book had been sold to Germany, the Netherlands, Sweden, and Finland before the book was even released in Norway. Kjærstad has garnered a level of international acclaim and success that is extremely rare among contemporary Norwegian authors.

In terms of the future, Norsk Rikskringkastning (the Norwegian Broadcasting Company) has discussed creating a dramatic television series based on the Jonas Wergeland novels, and Norwegian critics more or less unanimously agree that the books will be the subjects of academic theses and dissertations for years to come. Kjærstad scholarship has been consistently increasing in Denmark, Sweden, Germany, and the United States in recent years as well. As a result of the Nordic Council’s literature prize, requests for translations of Kjærstad’s work have also increased; an English translation of Forføreren (The Seducer) will be released in London in 2003. Jan Kjærstad continues to live and write in Oslo, Norway, and welcomes e-mail (please use the Kontakt link in the footer).

### Books
Kloden dreier stille rundt: Novellesamling (Oslo: Aschehoug, 1980);
Speil: leseserie fra det 20. århundre (Oslo: Aschehoug, 1982);
Homo Falsus, eller, det perfekte mord: Roman (Oslo: Aschehoug, 1984);
Det store eventyret (Oslo: Aschehoug, 1987);
Jakten på de skjulte vaffelhjertene, illustrated by Vivian Zahl Olsen (Oslo: Aschehoug, 1989);
Menneskets matrise: litteratur i 80-årene (Oslo: Aschehoug, 1989);
Rand: Roman (Oslo: Aschehoug, 1990);
Forføreren: Roman (Oslo: Aschehoug, 1993); translated by Barbara Haveland as The Seducer (London: Arcadia, forthcoming);
Hos Sheherasad, fantasiens dronning, illustrated by Judith Allan (Oslo: Damm, 1995);
Erobreren: Roman (Oslo: Aschehoug, 1996);
Menneskets felt: Essays (Oslo: Aschehoug, 1997);
Oppdageren: Roman (Oslo: Aschehoug, 1999);
Tegn til kjærlighet: Roman (Oslo: Aschehoug, 2002).

### Collections
Tekster 1984: en antologi, edited by Tron Jensen and Jan Kjærstad (Oslo: Gyldendal, 1983).

### Motion pictures
Det perfekte mord, screenplay by Barth and Isaksen, based on Jan Kjærstad’s novel, the Norwegian Film Institute/Isaksen, 1992.

### Other    
Tusen og én natt, Bind 1 og 2, selected and adapted by Jan Kjærstad, translated by Waldemar Brøgger (Oslo: Den norske bokklubben, 1988–1989);
“Kvanteloven” by Jan Kjærstad, in Veien langs linjene, eller, Hvordan vi ble forfattere, edited by Sissel Lie and Liv Nysted (Oslo: Gyldendal, 1993), 64–81;
“Blues” in Kolon Tekstsamling for VKI og VKII, 2nd edition (Oslo: Samlaget, 1995);
“Fram for det urene” in “Perioden 1945–2000. Litterære brytninger.” in volume 3 of Norsk tro og tanke (Oslo: Universitetsforlaget, 2001), 572–578.

### Selected periodical publications – uncollected
“Klagesang fra vernet mann,” response to Dag Solstad’s “Om meddelelsens problem” in Aftenposten, 1 July 1997;
“Fra profet til forteller” in Aftenposten, 19 May, 1999;
Kosovo debate, in Aftenposten, 14 June, 1999;
“Biografiens løgn” in Aftenposten, 27 January 2000;
“Fortellingens sannhet” in Aftenposten, 7 February 2000.

### Interviews
Dialoger II: Åtte forfattersamtaler, by Alf van der Hagen (Oslo: Oktober, 1996) – chapter 5, “En torpedo under Arken” interview with Jan Kjærstad, 138–172;
Dagbladet: på nettet, Kjærstad answers readers’ questions online, Dagbladet (5/10/99 and 2/23/00);
Jan Kjærstad with Michael Nielsen on Oppdageren, on Alfabet, DR Radio, (broadcast 10/20/99 and 2/7/01);
Jan Kjærstad with Huri Heftye on Maraton, Jan Kjærstad, Zentropa, 2000; selected footage.

### References
Per Thomas Andersen, “Repetitionens funksjon i Jan Kjærstads Homo falsus” in Fra Petter Dass til Jan Kjærstad: Studier i diktekunst og komposisjon (Oslo: Landslaget for norskundervisning (LNU) and Cappelen Akademisk Forlag AS, 1997), 310–328;
Stian Bromark, “Mot et nytt andre standpunkt i litteraturen,” in Vinduet No. 1 (2001);
Knut Brynhildsvoll, “Die neomanieristische ars combinatoria des Jan Kjærstad. Am Beispiel des Romans Rand.” in Präsentationen. Norwegische Gegenwartsautoren, edited by Knut Brynhildsvoll (Leverkusen 1990), pp. 177–208;
Knut Brynhildsvoll, “Kubistiske konsepsjoner i Jan Kjærstads roman Speil.” Guest lecture at the University of Budapest, April 1988, Papers in Scandinavian Studies, No. 4, 1990, 46–66;
Knut Brynhildsvoll, “Bildsprache und Sprachbilder in der Prosa und Prosatheorie Jan Kjærstads. Höchst vorläufige Überlegungen zur Poetik interpikturaler Kommunikation in literarischen Texten der Moderne.” with a summary in English, in Folia Scandinavica Posnaniensia, volume 6, Fall 1999, and in Schreibheft, Zeitschrift für Literatur, No. 54, Spring 2000;
Otto Hageberg, “Meining og meiningstap eller premoderne verdikrise. Arne Garborgs Trætte Mænd og Jan Kjærstads Rand.” På spor etter meining, 1994, 253–67;
Ingeborg R. Kongslien, “Mennesket i tekst og teori: Jan Kjærstads Homo Falsus,” Norsk Litterær Årbok (1988), 104–115;
Morten Kyndrup, “Som Norge for os alle,” Vinduet (2001);
Gitte Mose, “Don Jonas møder Don Juan og Don Johannes. Forfører og forførelse i Jan Kjærstads Forføreren og Søren Kierkegaards Enten Eller.” Norsk Litterær Årbok (1996), 121–32;
Gitte Mose, “Ord og menneske. Jan Kjærstads Det store eventyret som fantastisk tekst og eksistentiel fortælling” Litterære skygger, Ed. Torgeir Haugen. Oslo: LNU (1998), 221–236;
Øystein Rottem, Fantasiens tiår: Tekstens illusjoner og desillusjonens tekster. Et utvalg litteraturkritikk 1980–89 (Oslo: Aschehoug, 1990), 150–153; 240–244; 369–373;
Øystein Rottem, Jan Kjærstad: et forfatterhefte (Oslo: Biblioteksentralen, 2000)
Rushdie, Salman. “Is Nothing Sacred?” in Imaginary Homelands: Essays & Criticism, 1981–1991. Granta: London.


From: Tanya Thresher (ed.), Dictionary of Literary Biography, 20th Century Norwegian, Gale Group (2004)

Reprinted by permission of the Gale Group.
`

export default article