export const transformatorNo = `Han lyste rundt. Den svære grå innretningen foran ham var en oljetransformatorbryter, selv om han hadde vanskelig for å forstå det ­ at en bryter kunne være så stor. Jonas hadde sett for seg en vanlig type, som hovedbryteren i en sikringsboks eller noe sånt; denne ruvet som motorkassen på en bil. Ned i bryteren, fra skinnene i høyspentstativet, kom kablene som førte 5000 volt, som altså kanskje var levert av STK, og som først gikk gjennom kniver og sikringer og så ned i releene og de hvite gjennomføringsisolatorene som sto oppå bryteren. Jonas begynte å bli fortvilet. Han sluttet seg til at bryteren ble betjent med det rattet i støpegods som sto ut fra kassens front, for på en rød halvmåne i midten kunne han lese «Inne», og under en pil som pekte mot klokken, «Utkobling». Han forsøkte å dreie rattet i den retningen, men fikk ikke rikket det en millimeter, ante samtidig at han var farlig nær kablene som gikk ned i bryteren, 5000 dødbringende volt. Han visste allikevel ikke hvor farlig, at om han hadde ført hånden tilstrekkelig nær et av kablenes tilknytningspunkter, ville strømmen ha slått over og drept ham på flekken.

Jonas sitter med ryggen mot døren. Klokken er fem minutter på halv ni. Rundt om i blokkene benker folk seg foran radioapparatene for å høre Dickie Dick Dickens, spente på om Dickie vil klare å erobre plassen som konge i Chicagos underverden. Alle snakket om denne siste episoden, gjettet på utgangen, og Petter var den ivrigste av samtlige. Derfor satt Jonas her tross mørkeredsel, tross høyspenningsskilt. Han skulle endelig få hevnet seg på denne største av alle drittsekker. Og om du skulle undre deg, professor, spørre deg hvilken ond gjerning som kunne få et barn til å ville mørklegge et helt byggelag, bare for å få ram på én person, så må du vente, for svaret hører ikke hjemme her.

Jonas satt inne i noe stort, mørkt, farlig, ante kanskje allerede nå at dette var grunnsituasjonen i livet hans, sitte inne i noe ukjent og lete etter det punktet hvorfra man tross alt kunne påvirke, sette noe i gang. Hvis det da ikke var et desperat forsøk på å fylle sin tomhet. Bli en annen, bli noe. Han lyste rundt på måfå og fikk til slutt øye på en liten rød knapp på siden av jernkassen med rattet. Han akte seg bort til den. En siste sjanse. Han visste det var dumdristig. Tenkte på de enorme kreftene. Enn om det var feil og han falt død om da han rørte ved knappen. Eller omkom i et gnistregn idet hele greia kortsluttet. Jonas så det for seg, hvordan de ville finne ham som en innskrumpet kullbit, som de potetene de la i sølvpapir og glemte å ta ut av bålet.

Han kikker på klokken. Nøyaktig halv ni trykker han på knappen. Han registrerer at han fortsatt lever. Og at det skjer noe med et kjede og et tannhjul, at rattet beveger seg, at det nå står «Ute» på en grønn halvmåne. Jeg klarte det, tenker han. Det er dørgende stille, summingen er borte, som om også tilværelsens strøm er brutt. Gid du pisser på deg, tenker han med adresse til Petter.

Han kunne ikke se resultatet selv, men Ørn fortalte ham om det praktfulle synet, eller antisynet; Ørn hadde stått i vinduet og sett hvordan nettstasjonens forsyningsområde, hele Solhaug, gikk i svart, slik at også, langt viktigere for Jonas, de grønne kattøyene i radioapparatene sluknet, samtidig som stemmene døde hen. Og til alt hell hadde få reiseradio, og iallfall ikke Petter, og ingen av naboene som var hjemme i hans oppgang. Dessuten forsvant tanken på radioteatret i den alminnelige oppstandelsen ved et strømbrudd, liksom en mindre katastrofe, da folk hadde mer enn nok med å finne ut hva som hadde hendt og huske hvor de hadde lagt stearinlysene. Bare dagen etter kom Petter på å klage høylytt over at han hadde gått glipp av Dickie Dick Dickens: «Fy faen, og så siste episode 'a gitt!»

Det tok ikke mer enn snaue halvtimen før et par mann fra Oslo Lysverker var på pletten utenfor nettstasjonen i Hagelundveien. De gikk først inn i lavspentsiden. Jonas så lyset fra lyktene, hørte at de snakket seg imellom, mumlet noe om mulig overbelastning. Da de omsider låste opp døren til høyspentsiden, ble de så paffe, og redde, at Jonas klarte å smette ut og opp på Egiltomta som han kjente som sin egen bukselomme, før de så hvem det var.

Ryktet om at noen hadde vært inne i transformatoren kom ut og ble flittig kommentert av Solhaugs beboere – enkelte snakket om kommunister – men ingen fikk noen gang greie på hvem det var. Jonas syntes allikevel Petter så på ham med en viss forundring, som om han hadde oppdaget at Jonas var ladet på en helt ny måte, var en annen person. Med tiden kom Jonas til å frykte at denne søte hevnen skulle få dystre følger – noe han fikk bekreftet seks år senere da han spaserte gjennom Transilvania sammen med Laila. Innerst inne, og tross avstanden i tid, trodde Jonas alltid at overgrepet mot Laila skyldtes noe han selv hadde gjort, at det var en konsekvens av at Petter ikke fikk med seg siste episode av et krimhørespill.

Den umiddelbare reaksjonen var uansett nytelse. Han lå og kjælte med tanken på hvordan et trykk på en så liten knapp kunne forårsake så mye, hvor lett det var å påvirke mange mennesker, og samtidig, i det samfunnet han levde. Dette var ellers første gang Jonas Wergeland synkroniserte folks oppmerksomhet. Siden skulle han gjøre det igjen, i større målestokk, bortsett fra at folk nå, en hel nasjons innbyggere, frivillig slukket lamper så de kunne sitte i halvmørket og koble ut alt annet til fordel for det lyset som TV-programmene hans ga dem.`

export const transformatorEn = `He shone the light round. The great grey appliance before him was an oil-immersed transformer switch, even though he found it hard to believe – that a switch could be so large. Jonas had imagined the ordinary sort, like the main switch in a fuse box or something similar; this one loomed up like the engine casing of a car. Five thousand volt cables led into the switch from the bars on the high voltage frame, which perhaps also had been supplied by STK, after first passing through knife-switches and fuses and then down into the relays and the white lead-in insulators above the switch. Jonas began to despair. He decided that the switch must be operated by the cast hand wheel that protruded from the front of the casing because, on a red crescent in the middle he could read the word "On" and beneath it an arrow pointing anti-clockwise, "Off". He tried to turn the wheel in that direction, but couldn't budge it a millimetre, realising at the same time that he was dangerously close to the cables that led into the switch, five thousand lethal volts. Though he didn't know how dangerously close, that had he moved his hand sufficiently near one of the cables' switch-on points, the current would have short-circuited and killed him on the spot.

Jonas sits with his back to the door. The time is eight twenty-five. All around in the tenements people are taking their places in front of their radios, ready to listen to Dickie Dick Dickens, on tenterhooks to hear whether Dickie will manage to win the throne of Chicago's underworld for himself. Everyone was talking about this final episode, guessing its outcome, and Petter was the keenest of the lot. That's why Jonas was here, in spite his fear of the dark, in spite of the high voltage warning. He would at last be revenged on that dirtiest of all rotters. And in case you're wondering, professor, asking yourself what evil deed could make a child want to plunge an entire estate into darkness – just to hit home at one person, you'll just have to wait, because the answer doesn't belong here.

Jonas sat inside something big, dark and dangerous, perhaps even now with an inkling that this was to be the essence of his life, being inside something unknown, but still seeking the point from which to influence, to put something in train. That is, if it wasn't a desperate attempt to fill his emptiness. Be someone else, be something. He shone his torch round at random and eventually caught sight of a small red button on the side of the iron casing with the hand wheel. He edged over to it. One last chance. He knew it was foolhardy. He thought of the colossal power. What if it was the wrong one and he fell down dead as soon as he touched the button. Or died in a shower of sparks as the whole thing short-circuited. Jonas imagined it all, how they would find him, a shrivelled lump of charcoal, like the potatoes they wrapped in aluminium foil and forgot to take out of the fire.

He looks at his watch. At precisely half past eight he presses the button. He registers that he's still alive. And that something is happening with a chain and a cogwheel, that the handwheel is moving, that a green half-moon now displays the word "Off". I did it, he thinks. It's as still as a grave, the humming has stopped, as if the current of existence has also been cut off as well. Hope you're wetting your knickers, he thinks addressing the thought to Petter.

He couldn't see the result for himself, but Eagle told him about the wonderful sight, or non-sight; Eagle had been standing at the window and had seen how the sub-station's supply area, the whole of Solhaug, went dark, and, much more important to Jonas, that the green cat's-eyes belonging to the radios went out, and the voices faded away. And by good fortune few people had portable radios, not Petter anyway, and none of the neighbours who were at home in his block. And the notion of radio drama evaporated in the general consternation at a power cut, as if it was some minor catastrophe, and people had enough to do finding out what had happened and remembering where they'd put the candles. The very next day Petter began moaning loudly about how he'd missed Dickie Dick Dickens: "The last episode and all, sod it!"

In less than half an hour two men from the Oslo Electric Company were there, outside the sub-station in Hagelundveien. First they went into the low voltage side. Jonas saw the light from their torches, heard them talking, mumbling something about a possible overload. When they finally unlocked the door to the high voltage side, they were so scared and surprised, that Jonas managed to slip out and up to Egiltomta, which he knew like the back of his hand, before they could get a look at him.

Rumours that someone had been in the transformer got out and caused much comment amongst Solhaug's residents ­ some of whom spoke of communists – but no one ever discovered who it was. However, Jonas had the feeling that Petter regarded him with a certain awe, as if he'd discovered that Jonas was charged in a totally new way, was another person. In time Jonas began to fear that this sweet revenge would have doleful consequences – something that was confirmed six years later as he meandered through Transilvania with Laila. Deep down, and despite its remoteness in time, Jonas always believed that the violation of Laila was something he was responsible for, that it stemmed from the fact that Petter never got to hear the final episode of a radio whodunit.

However, his immediate reaction was one of pleasure. He lay relishing the thought that pushing one tiny button could have such huge consequences, how easy it was to affect lots of people, and people amongst whom he lived in as well. This, by the way, was the first time Jonas Wergeland synchronised people's attention. Later he would do so again, on a larger scale, though then an entire nation would voluntarily switch off lights so they could sit in semi-darkness and shut out everything except the brightness that his television programmes brought them.`