const perBuvikReview = 
`Alle epoker er preget av motsetninger og paradokser, og vår egen er ikke noe unntak. Ta for eksempel dagens voldsomme interesse for biografiske og selvbiografiske skildringer og opptattheten av det private. Det er jo underlig at denne tendensen er så markert nettopp i en tid da ledende internasjonale tenkere og deres tilhengere ikke bare har avvist, men også i teorien umuliggjort biografien som genre. Men her som ellers er det gjerne ytterpunktene som blir lagt merke til: på den ene side de naive biografer som skriver som om ingenting avgjørende nytt var tenkt om forholdet mellom tekst og liv; på den annen side de rabiate teoretikere som lukker øynene for at livsskildringer tross alt kan skrives på forskjellige måter, og at biografien også fyller et erkjennelsesbehov.

For alle med den minste interesse for denne problemstillingen er Jan Kjærstads bøker om Jonas Wergeland viktige. I 1993 kom Forføreren, og nå foreligger Erobreren, som blir kalt den definitive biografi om denne personen som må få en plass i nyere norsk litteraturhistorie på linje med Ask Burlefot og Wilfred Sagen. I Forføreren var hovedspørsmålet: «Hvordan henger et liv sammen?». I Erobreren er det tre hovedspørsmål: «Hvordan blir man en erobrer?»; «Hvordan blir man en morder?»; og «Går det an å forandre et liv ved å fortelle det?». Perspektivet er, som vi ser, ikke helt det samme som før. Det skyldes i korthet følgende: I Forføreren kommer Jonas hjem fra en utenlandsreise og finner sin kone Margrete død på gulvet; i Erobreren blir han selv anklaget for mordet, og tilstår også etter en stund å ha begått det. Hvordan blir man altså en morder? Dette spørsmålet, og de to andre, blir stilt om og om igjen utover i teksten, og fungerer som besvergende ledemotiv. Ingen av dem blir vel egentlig besvart, men det er også meningen, for de kan knapt besvares. Imidlertid kan de belyses, og det gjør Kjærstad til gagns – og med bravur. La meg prøve å gi et inntrykk.

Jeg holdt på å skrive at jeg skulle begynne med begynnelsen, men et av Kjærstads poeng er nettopp at det er meget komplisert å avgjøre hva en begynnelse virkelig er. Uansett hvor fortelleren forsøker å nøste opp Jonas Wergelands liv, dukker det opp nye spor som fører både framover, utover og bakover: Det man derfor kan tro er begynnelsen, har alltid en annen begynnelse, og forestillingen om en rett linje fra barndommens uskyld til manndommens forbrytelse avslører seg som ren illusjon. Er da livet et eneste virvar, blottet for all påviselig sammenheng? Er alt vilkårlig, uten feste i noe forutgående? Noen ekstreme post-modernister kan muligens hevde et slikt syn, men det ligger fjernt fra Kjærstads posisjon. All erfaring tilsier, synes han å mene, at det må være visse sammenhenger i et menneskeliv, men de er ikke kausale og lett forklarlige – snarere gåtefulle, for ikke å si mysteriøse. Sagt litt mer presist er alle menneskelige karakterer og handlinger for Kjærstad overbestemte, dvs. bestemte av flere faktorer på én og samme tid, uten at én faktor utvetydig peker seg ut som mer avgjørende enn de andre.

En slik tanke gjennomsyrer ved nærmere ettersyn romanen på alle nivåer. Således har Erobreren ikke engang bare én forteller, men to, eller bedre: én forteller og én skriver. Den teksten vi leser, er ført i pennen av en forhenværende historieprofessor, men den er i alt vesentlig diktert av en ukjent, svartkledd kvinne. Hun kommer ham til unnsetning da han står fast, overveldet av alt det sprikende materialet han har samlet for å løse sin oppgave. Men tro nå likevel ikke at det dreier seg om mekanisk nedskrivning av en muntlig beretning.

For det første blir jo også informasjonen om den muntlige fortellersken gitt i den skriftlige teksten vi leser. For det andre er det flere trekk ved den fremmede hjelperen som ikke gjør det urimelig å påstå at Erobreren mindre er inspirert av en muntlig fortelling enn av et litterært verk, nemlig Tusen og én natt. Den berømte arabiske eventyrsamlingen har for øvrig også en innfløkt tilblivelseshistorie der muntlig og skriftlig blander seg. Og den handler ikke bare om Aladdin, Ali Baba, Sinbad, osv., men likeledes om Scheherazade, som forteller og forteller på harde livet for å unngå å bli drept. Den ukjente svartkledde i Kjærstads roman synes for sin del å ha et ønske om å oppheve hovedpersonens drap og tilståelse og forhindre hans straff ved hjelp av sin mange fortellinger: «Går det an å forandre et liv ved å fortelle det?».

Men Tusen og én natt er sannelig ikke det eneste litterære verk Erobreren står i et nært forhold til. Johan Borgens Lillelord-trilogi er opplagt; Borgen opptrer til og med selv i romanen. Mindre selvsagt for de fleste er nok den rollen Goethes berømte (men lite leste) dannelsesroman Wilhelm Meisters læreår spiller. Både i Erobreren og i Wilhelm Meister har tårnet en sentral plass; i begge verk er det andre mennesker som loser hovedpersonen gjennom livet fram til selvrealiseringen (for det er jo på sett og vis dét også den ukjente fortellersken gjør); og begge verk slutter med en utopisk begynnelse («Livet mitt har begynt på nytt fra og med nå», er siste setning hos Kjærstad). Attpå til sammenligner den fremmede fortellersken Jonas med Saul, Israels første konge. Hos Goethe framholdes nettopp Sauls lykke som et bilde på hvor heldig Wilhelm er med sitt liv. Her er nok å ta av for litterater, som man skjønner.

Men Kjærstad har slett ikke skrevet en bok bare for dem. Tvert om gad jeg se den leser som ikke lot seg fascinere av hans sprudlende fortellinger om å være barn og ungdom i etterkrigstidens Norge, for det er ikke minst dét romanen handler om. 50-, 60- og 70-årenes Grorud og Oslo i Kjærstads versjon oppviser i hvert fall forbløffende samsvar med det litt mer landlige stykke Norge hvor jeg selv trådte mine barnesko i Gerhardsen-epoken. Den ukjente og til tider skremmende fortellersken, som kanskje likevel ikke så ukjent – for har hun ikke også påfallende likhetstrekk med Goethes Mefisto? ­ er for øvrig inne på at den beste innfallsvinkelen for å forstå personen Jonas Wergeland er å danne seg et begrep om det landet og det folket han er en del av. Kanskje viser hans navn mindre til et individ enn til en mentalitet, undres den skrivende professor, som i den tiden han arbeidet på universitetet bekjente seg til den såkalte Annales-skolen og den vitenskapelige retningen som går under betegnelsen mentalitetshistorie. Hva særkjenner Norge? spør fortellersken. Tomhet, svarer hun. Uendelig tomhet. Hele Jonas' liv ser hun i lys av det. For hva om opphavet til hans ulike bedrifter, både som elsker og som programskaper i fjernsynet, ligger nettopp her? «I den tilbøyeligheten enhver har til å fylle tomheten med innhold».

Fortellersken framsetter dessuten en besnærende hypotese. Jonas Wergeland, som dyrkes som en gud av sine landsmenn på grunn av sin originale portrettserie om store norske personligheter, er i realiteten høyst alminnelig: et typisk gjennomsnittsmenneske. Professoren beklager seg stadig over at det vesentlige i en livsskildring aldri ligger i det som kan skildres, men i mellomrommene mellom den rekken av historier en biografi består av, i «disse svarte hullene som skapes i skjæringspunktet mellom to historier». Hypotesen om Jonas' gjennomsnittlighet er nettopp basert på iakttakelse av det mellomliggende, det som ikke ligger oppe i dagen. Den forklarer også til en viss grad Jonas' oppfinnsomme innfallsvinkler som portrett-skaper. I første omgang ble han som sagt hyllet for dem, men i neste omgang ble han hudflettet – «for å ha tatt bort storheten, selve helheten, i livet til de berømthetene han portretterte». Med andre ord for å ha gjort dem for alminnelige: lik seg selv, lik TV-seerne, lik enhver. Med en ørliten vri på en av fortellerskens uttalelser, hadde han forstått at enhver vellykket biografi er enhvers biografi.

Professoren mener å kunne fastslå at det er noe demonisk ved Jonas Wergeland, og når han lar seg nøde av forlaget til å skrive den endelige boken om ham, er hans dypeste målsetting å forklare hva dette demoniske består i. Til sist tror han også at han har fått tak i det. For motivet for å myrde konen, den på alle måter imponerende Margrete Boeck, er, kommer han fram til, mindre sjalusi enn redselen for å bli avkledd og måtte framstå som det han er: et helt middelmådig menneske. Så lenge han levde med den storslagne Margrete, kunne ingen tvile på at også han var spesiell. Gikk hun fra ham, ble dét en illusjon som ikke lenger kunne opprettholdes.

Dessverre må jeg gi meg med dette. Jeg gjør det motvillig, for maken til tekst er det ikke ofte jeg har fått til anmeldelse. Erobreren er etter mitt syn enda bedre enn Forføreren. Hvis det er riktig at alle virkelige biografier i realiteten er fiksjoner, hvorfor kan da ikke flere ta konsekvensen av det og heller lese fiktive biografier? For det er de som er de sanne. Kjærstads verk om Jonas Wergeland er det aller beste eksempel på det.`

export default perBuvikReview